import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";

export const metadata: Metadata = {
  title: "Shaped | Welcome",
  description: "Redners different kinds of services",
};

export const raleway = Raleway({
  variable: "--raleway",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full h-screen ${raleway.variable} antialiased relative pt-[132px]`}
      >
        <Header className="bg-white h-[132px] fixed top-0 left-0 z-[100]" />
        {children}
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ol className="list-inside list-decimal text-sm text-center sm:text-left font-[family-name:var(--font-geist-mono)]">
//         </ol>
//         {children}
//       </body>
//     </html>
//   );
// }
